### ISSUE TITLE
Update apps logo to show up against github's white background.

### ISSUE THREAD

**Issue by AlvaroIsrael** [AlvaroIsrael/gobarber-app#132]
Update apps logo to show up against github's white background.

**Comment by GitauHarrison** [comment]
Neat README!

One thing though, when I try to update my profile page after signing in, I get a flat message "There was a problem updating profile. Please try again!"

I, as user, would appreciate a more informative flash message such as 'Weak password. Please try again'.

Psst: Should the actual appointment dates show up? Morning and Late rows are empty even after I select a date.

**Comment by AlvaroIsrael** [comment]
Hey @GitauHarrison about the password 'strength meter' it would be a nice enhancement indeed. Maybe i will implement that in the future or you could also implement that yourself and create a pull request for me to review and aprove.

About the empty dates: It is behaving like that because the app is not complete yet. The idea is for the users to use the mobile app to create the appointments and the desktop version as a 'control panel' to manage appointments for that day. Once I finish the mobile version them the appointments will show. But if i am not mistaken, the appointments creation can be made also using the swagger but i am not 100% sure tough, have to look into it.

When you detect a bug or some strange behavior you can always open a new 'Issue', because this one is just for the Background logo!
