### ISSUE TITLE
The create account link is hidden with the link to go to the Github project of the app.

### ISSUE THREAD

**Issue by r-e-d-ant** [AlvaroIsrael/gobarber-app#187]
Hello, It is not possible to go the create account page because the link to go there is hidden with another link togo to the Github project of the app.

Maybe add a spacing.

![issue](https://user-images.githubusercontent.com/66163130/190643455-64643722-836d-480c-b0d0-8b863da85703.png)

**Comment by AlvaroIsrael** [comment]
Hey @r-e-d-ant , thanks for the warning. Is it something you would be willing to contribute, maybe open up a PR with fix?

**Comment by r-e-d-ant** [comment]
Ok i can do it

**Comment by AlvaroIsrael** [comment]
@r-e-d-ant wait for me to fix the pipelines problems before I can release it to production. See #189 for more info.

**Comment by r-e-d-ant** [comment]
ok ok !
